[tool.poetry]
name = "code"
version = "0.1.0"
description = ""
authors = ["Ugur Cayoglu"]

[tool.poetry.dependencies]
python = "^3.8"
Cartopy = "^0.19.0"
numpy = "^1.21.1"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
